### ISSUE TITLE
Consistency in topic descriptions

### ISSUE THREAD

**Issue by mhvingelby** [CodeMyst/BrackeysForumIssueTracker#13]
The 2D and 3D sub forums have got pretty much the same description, except for one word. Personally it’s bugging me a bit but for sure it’s a minor thing.
Edit: I also just noticed a minor grammar mistake in the 3D sub forum.

**Comment by Duxez** [comment]
If you'd mind telling us what the grammar error is we'd love to fix it! :)

**Comment by TheDutchMagikarp** [comment]
The grammar problem is fixed now. Did not edit the descriptions other than that.
