### ISSUE TITLE
Following Comment URL will not highlight the actual comment

### ISSUE THREAD

**Issue by AquaXV** [CodeMyst/BrackeysForumIssueTracker#16]

**Comment by AquaXV** [comment]
Example; https://forum.brackeys.com/discussion/comment/261#Comment_261

**Comment by AquaXV** [comment]
Comments are li items with as ID their comment number: (XPath)
//*[@id="Comment_261"]

**Comment by Duxez** [comment]
How'd you even manage to grab a comment link?

**Comment by AquaXV** [comment]
moderation tab in dashboard.

**Comment by Duxez** [comment]
Added in next update

**Comment by AquaXV** [comment]
https://forum.brackeys.com/discussion/417/making-a-multiplayer-game-read-this#Comment_580
Not yet fixed.

**Comment by Duxez** [comment]
It highlights the comment in the link

**Comment by AquaXV** [comment]
wtf it didn't 2 minutes ago 🤔

**Comment by Duxez** [comment]
Cache?

**Comment by AquaXV** [comment]
Dunno, is fixed now though.
