### ISSUE TITLE
[QOL] Gray out "new thread" when lacking permissions

### ISSUE THREAD

**Issue by SnowyToo** [CodeMyst/BrackeysForumIssueTracker#2]
Mostly an intuitive QOL change for the "Announcements" tab. It's currently possible to click the button but be booted to an empty "Permission Problem" page.

Suggestion to either make the button non-interactable, if possible. Alternatively, fitting the "permission problem" page to the forum style and having a button on it to return to the main page could work as well.

**Comment by Duxez** [comment]
New thread button only shows up if the user is allowed to post in the next update
