### ISSUE TITLE
Unable to delete a forum reply.

### ISSUE THREAD

**Issue by salty-sweet** [CodeMyst/BrackeysForumIssueTracker#20]
I don't know if this is a bug or entirely not featured, but deleting a forum reply is not possible in anyway.
![image](https://user-images.githubusercontent.com/36786920/82722819-9264e980-9cfc-11ea-8916-be9ed1b63dfb.png)

An attempt to edit a reply to an empty reply only showed this instead:
![image](https://user-images.githubusercontent.com/36786920/82722812-84af6400-9cfc-11ea-9f57-1932f4e18096.png)

**Comment by Duxez** [comment]
You're not able to delete reply's no.
