### ISSUE TITLE
[QOL] Improve text formatting in the "Guidelines!" post

### ISSUE THREAD

**Issue by SnowyToo** [CodeMyst/BrackeysForumIssueTracker#3]
This sublist not being indented makes it feel like a bit of a confusing mess, especially because the forum _has_ the support for proper sublists.
![Knipsel](https://user-images.githubusercontent.com/34379309/82479989-6d416280-9ad3-11ea-959c-54ab7f5e9ebe.png)

Additionally, formatting isn't consistent, with some lines having the bold "title" part be a header for the point (see above picture), and some lines having the bold "title" part be in-line with the rest of the point (see below).
![Knipsel](https://user-images.githubusercontent.com/34379309/82480321-eb056e00-9ad3-11ea-86f4-fdc5cba2dbec.png)

**Comment by CodeMyst** [comment]
I fixed the inconsistencies and some spelling mistakes. If you find any more issues related to the guidelines feel free to reopen the issue.
