### ISSUE TITLE
[Bug?] "Support us on Patreon" not lighting up on mouse hover

### ISSUE THREAD

**Issue by SnowyToo** [CodeMyst/BrackeysForumIssueTracker#5]
The "Support us on Patreon" text on the bottom of the page does not light up when hovering over it, despite being a button/clickable. 
In contrast, the gray text in "Powered by Brackeys" _does_ light up when hovering over it, despite _not_ being a button/clickable.

Additionally, only the "Patreon" text is clickable. If all text is supposed to light up on hover (like it does with the gray text in "Powered by Brackeys"), you'd presumably want it to be clickable in its entirety.

**Comment by Duxez** [comment]
Fixed in next update
